<a href="https://colab.research.google.com/github/samnocera05-ui/mis433/blob/main/Copy_of_data_summarization_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise: Data Summarization

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Install required packages
!pip install -q nycflights13

from nycflights13 import flights
flights.head()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 93.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for nycflights13 (setup.py) ... done

/usr/local/lib/python3.13/dist-packages/nycflights13/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename as _rf

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

## DataFrame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two-letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [4]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

## Exercises

Write Python scripts to answer the following questions.

In [5]:
# How many distinct airplanes are there in this dataset?
flights['tailnum'].nunique()

4043

In [6]:
# Which hours of the day are the busiest?
# List the top 5 hours with the most flights.
flights['hour'].value_counts().head()

hour
8     27242
6     25951
17    24426
15    23888
16    23002
Name: count, dtype: int64

In [7]:
(
    flights
    .groupby('hour')
    .agg({'flight':'count'})
    .sort_values('flight',ascending=False)
    .head()
)

      flight
hour
8      27242
6      25951
17     24426
15     23888
16     23002

In [8]:
# Find all flights (identified by 'carrier' and 'flight')
# that always depart at least 60 minutes late.
df1 = flights.groupby(['carrier', 'flight']).agg({'dep_delay': 'min'})
df1[df1['dep_delay']>= 60]

                dep_delay
carrier flight
9E      3283        104.0
        3297        120.0
        3546         64.0
        3583         95.0
        3588        115.0
        3682         66.0
        3760        217.0
B6      205          82.0
DL      390         334.0
        462         125.0
        809         298.0
        917         157.0
        2390         92.0
EV      4151         67.0
        4320         95.0
        4564         91.0
        4617        128.0
        5015         63.0
        5062        111.0
        5071         92.0
        5083         98.0
        5117        219.0
        5294        192.0
        5358         78.0
        5409         87.0
        5425         62.0
        5478        242.0
        5629         71.0
        5668        106.0
        5839         65.0
        5855        209.0
        6082        153.0
        6093        128.0
F9      2001         65.0
OO      8500         67.0
UA      18           95.0
        125          89.0
        348          93.0
        546          60.0
        640         115.0
        945          62.0
        993          69.0
        1510        278.0
US      1226        147.0
WN      217         195.0
        521         346.0
        718          78.0
        1019        203.0
        2521         79.0
        2529         75.0
        3032         90.0
        3791        151.0
YV      3799        168.0

In [24]:
# How many flights always depart at least 60 minutes late?
(
    flights
    .groupby(['carrier', 'flight'])
    .agg({'dep_delay': 'min'})
    .query('dep_delay>= 60')
)

                dep_delay
carrier flight
9E      3283        104.0
        3297        120.0
        3546         64.0
        3583         95.0
        3588        115.0
        3682         66.0
        3760        217.0
B6      205          82.0
DL      390         334.0
        462         125.0
        809         298.0
        917         157.0
        2390         92.0
EV      4151         67.0
        4320         95.0
        4564         91.0
        4617        128.0
        5015         63.0
        5062        111.0
        5071         92.0
        5083         98.0
        5117        219.0
        5294        192.0
        5358         78.0
        5409         87.0
        5425         62.0
        5478        242.0
        5629         71.0
        5668        106.0
        5839         65.0
        5855        209.0
        6082        153.0
        6093        128.0
F9      2001         65.0
OO      8500         67.0
UA      18           95.0
        125          89.0
        348          93.0
        546          60.0
        640         115.0
        945          62.0
        993          69.0
        1510        278.0
US      1226        147.0
WN      217         195.0
        521         346.0
        718          78.0
        1019        203.0
        2521         79.0
        2529         75.0
        3032         90.0
        3791        151.0
YV      3799        168.0

In [12]:
# Find all United Airlines (UA) flights (identified by 'carrier' and 'flight')
# that depart (at least) 60 minutes late.
df1 = flights.groupby(['carrier', 'flight']).agg({'dep_delay': 'min'}).reset_index()
df1[(df1['dep_delay']>=60) & (df1['carrier'] == 'UA')]

     carrier  flight  dep_delay
3101      UA      18       95.0
3147      UA     125       89.0
3300      UA     348       93.0
3489      UA     546       60.0
3572      UA     640      115.0
3775      UA     945       62.0
3801      UA     993       69.0
4167      UA    1510      278.0

In [25]:
# How many United Airlines (UA) flights depart (at least) 60 minutes late?
(flights[flights.carrier=='UA']
.groupby(['carrier', 'flight'])
.agg({'dep_delay': 'min'})
.query('dep_delay >= 60')
)

                dep_delay
carrier flight
UA      18           95.0
        125          89.0
        348          93.0
        546          60.0
        640         115.0
        945          62.0
        993          69.0
        1510        278.0

In [35]:
# Which flights always arrived on time in December?
(
    flights[flights.month== 12]
.groupby(['carrier', 'flight'])
.agg({'arr_delay': 'min'})
.query('arr_delay <=0')
)

                arr_delay
carrier flight
9E      2900        -36.0
        2901        -22.0
        2902        -23.0
        2903        -36.0
        2904        -32.0
...                   ...
WN      4976        -17.0
YV      2807        -11.0
        2885        -38.0
        2889        -46.0
        3771        -12.0

[1870 rows x 1 columns]

In [21]:
# How many flights always arrived on time in December?
(
    flights[flights.month == 12]
    .groupby(['carrier', 'flight'])
    .agg({'arr_delay': 'max'})
    .query('arr_delay<=0')
)

                arr_delay
carrier flight
9E      2909         -7.0
        2919        -32.0
        2934        -22.0
        2939        -21.0
        2950          0.0
...                   ...
WN      4313        -18.0
        4337        -22.0
        4490         -2.0
        4514         -2.0
        4976        -17.0

[330 rows x 1 columns]

In [26]:
# Create a dataframe 'cancelled' for all cancelled flights.
# Assumption: flights that are not cancelled should have values for dep_time.
cancelled = flights[(flights.dep_time.isna())]
cancelled

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
838,2013,1,1,NaN,1630,NaN,NaN,1815,NaN,EV,4308,N18120,EWR,RDU,NaN,416,16,30,2013-01-01T21:00:00Z
839,2013,1,1,NaN,1935,NaN,NaN,2240,NaN,AA,791,N3EHAA,LGA,DFW,NaN,1389,19,35,2013-01-02T00:00:00Z
840,2013,1,1,NaN,1500,NaN,NaN,1825,NaN,AA,1925,N3EVAA,LGA,MIA,NaN,1096,15,0,2013-01-01T20:00:00Z
841,2013,1,1,NaN,600,NaN,NaN,901,NaN,B6,125,N618JB,JFK,FLL,NaN,1069,6,0,2013-01-01T11:00:00Z
1777,2013,1,2,NaN,1540,NaN,NaN,1747,NaN,EV,4352,N10575,EWR,CVG,NaN,569,15,40,2013-01-02T20:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

In [27]:
# Look at the number of cancelled flights per day.
# Find the top 10 days with the most cancelled flights.
(
    cancelled
    .groupby(['year','month','day'])
    .agg({'flight': 'count'})
    .sort_values('flight', ascending =False)
    .head(10)
    )

                flight
year month day
2013 2     8       472
           9       393
     5     23      221
     12    10      204
     9     12      192
     3     6       180
           8       180
     12    5       158
           14      125
     6     28      123

In [28]:
cancelled[['year', 'month', 'day']].value_counts().head(10)

year  month  day
2013  2      8      472
             9      393
      5      23     221
      12     10     204
      9      12     192
      3      6      180
             8      180
      12     5      158
             14     125
      6      28     123
Name: count, dtype: int64

In [29]:
# Which carrier has the worst average arrival delay?
(
    flights
    .groupby('carrier')
    .agg({
        'arr_delay':'mean'
    }).sort_values('arr_delay', ascending= False)
    .head(1)

)

         arr_delay
carrier
F9       21.920705

In [30]:
# Which plane (tailnum) has the worst on-time record?
(
    flights[flights.dep_delay.notna()]
    .groupby('tailnum')
    .agg({'dep_delay':'mean'})
    .sort_values('dep_delay')
    .tail(5)
)

         dep_delay
tailnum
N851NW       233.0
N911DA       268.0
N587NW       272.0
N922EV       274.0
N844MH       297.0

In [31]:
# What time (hour) of day should you fly if you want to avoid delays as much as possible?
(
    flights
    .groupby('hour')
    .agg({'dep_delay': 'mean'})
    .sort_values('dep_delay', ascending=False)
    .head(5)

)

      dep_delay
hour
19    24.784791
20    24.304105
21    24.195743
18    21.110082
17    21.100606

In [32]:
# For each destination, compute the total minutes of arrival delay.
(
    flights
    .groupby('dest')
    .agg({'arr_delay':'sum'})
)

      arr_delay
dest
ABQ      1113.0
ACK      1281.0
ALB      6018.0
ANC       -20.0
ATL    190260.0
...         ...
TPA     54749.0
TUL      9896.0
TVC      1232.0
TYS     13912.0
XNA      7406.0

[105 rows x 1 columns]

In [33]:
# Find days whose average arrival delay is greater than 1 hour.
(
    flights
    .groupby(['year', 'month', 'day'])
    .agg({'arr_delay': 'mean'})
    .query('arr_delay>60')
)

                arr_delay
year month day
2013 3     8    85.862155
     5     23   61.970899
     6     13   63.753689
     7     22   62.763403

In [34]:
# Find the number of carriers between each pair of origin and destination.
(
    flights
    .groupby(['origin', 'dest'])
    .carrier
    .nunique()
)

origin  dest
EWR     ALB     1
        ANC     1
        ATL     4
        AUS     2
        AVL     1
               ..
LGA     SYR     2
        TPA     2
        TVC     2
        TYS     1
        XNA     2
Name: carrier, Length: 224, dtype: int64